### ISSUE TITLE
Proposed additions (XMLOutput and SimpleLogCollector)

### ISSUE THREAD

**Issue by stolstov** [cpptest/cpptest#16]
Could you take a look at this diff if you would like to adopt these changes?
https://github.com/cpptest/cpptest/compare/master...Esri:sergey/xmloutput

Added XMLOutput class for xml output in the compatible format with cppunit
Added SimpleLogCollector output class, that allows to run the tests into it and then you can
playTo into the output of your choice, so that you could generate HTML and XML at the same run.

**Comment by hartwork** [comment]
Hi Sergey,

I had a quick look. I'll just do a braindump here if that's okay:
- Rather than adding more Visual Studio files, I think this project needs a migration to CMake which can generate MSVC solution and project files out of the box.
- I haven't gotten beyond C++98/03 myself so I'm not 100% sure which later version of the language this new code is using. Does the new code support C++11? We have `AX_CXX_COMPILE_STDCXX_11` in `configure.ac` right now. Just asking, because without a pull request I have now idea what the CI would say to this code.
- We should start using AppVeyor so all the Windows-specific code is actually covered.
- `&apot;` needs to be `&apos;` with `s` — looks like a typo.
- If you turn this into a pull request, please make sure it#s rebase on top of latest master and is free of merge commits.

What do you think?

PS: Pull request #8 of 2017 looks related.

**Comment by stolstov** [comment]
Let me see what I can do. I can remove the visual studio files, we'll keep them in our fork. However, I don't know much about CMake, so I'd need your help there. The new code is compatible with c++11, but does not really make use of it. I'll fix the typo with apos. The older pull request was by mistake.

**Comment by stolstov** [comment]
@hartwork Could you check this diff if it looks acceptable?
https://github.com/cpptest/cpptest/compare/master...Esri:sergey/xmloutput_cpptest

**Comment by hartwork** [comment]
Hi!

Is there a particular reason why we continue with this kind of diff display rather than a pull request where the CI can have a word and I can comment on the whole diff, not just single commits, so that the comments persist?

With my picky hat on, here's a few things I noticed:
- The two new files lack copyright headers
- The new code in `mytests.cpp` is not ready for consumption by a general audience, e.g. I see:
  - commenting out existing code
  - hardcoded `c:/temp/test_output`?!
  - `if (true)` like constructs
  - function `cmdline` still needs to be extended
- The `a_1231422` changes in `cpptest-assert.h` seem unrelated and do not explain itself
- The `Test::correct` changes in `utils.cpp` seem unrelated; looks like the right direction tough.  I'd want to add protection against return 0 or 100 for anything that is not true 0 or 100, when we go this route.
- The `int -> std::streamsize` change in `time.cpp` is a warning fix?  Seems unrelated, separate commit please.
- The `exception catching` change in `suite.cpp` seems unrelated, separate commit please. That's issue #3 by the way :smile: 
- `#if (defined(__WIN32__) || defined(WIN32))` should probably be `if defined(_WIN32)`

For the next iteration, please please please please use a pull request.

**Comment by stolstov** [comment]
@hartwork This is used in a small project for a couple of years with the changes as submitted. I hope it worth a shot you may want to adopt these changes without much work on my side :)
The changes in the mytest.cpp demonstrate how to use the new code, can be removed. The changes in cpptest-assert.h are to avoid recalculating the expression, and to ensure assertion when one of values is NAN which is important for what we use this for. The weird vairable name is to avoid compiler warnings if variable name collides in external scope. Test::correct is don't remember the reason for the change can be removed.

**Comment by hartwork** [comment]
Without a license header I cannot use the code. It's a pity that you want to continue maintaining this code in a fork rather than getting it in here, but I understand that time can be a scarce resource. To be clear, I don't use cpptest myself (but GTest) these days so my review was for you and the community.

**Comment by stolstov** [comment]
@hartwork Could you post a sample header with a custom copyright statement?

**Comment by hartwork** [comment]
If you're the sole author of this code:
```
// ---
//
// CppTest - A C++ Unit Testing Framework
// Copyright (c) 2019 Sergey Tolstov
//
// ---
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the
// Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.
//
// ---
```
If there are more authors, add one line `// Copyright (c) 2019 ${first} ${last}` per person please.

**Comment by stolstov** [comment]
I've added the header to the new files in both branches.
